#!/usr/bin/env bash

COMPILER=src/main/wallpaper/wallpaperCompiler.py
TARGET_DIR=src/main/test/
VENV="echo $(echo $VIRTUAL_ENV)"
PYTHON_DIR="$VENV/bin/python"

if [[ $VENV == "" ]]; then
    echo "Voce deve possuir um virtualenv para python."
    echo "Após possuir, execute 'pip install -r requirements.'"
    exit
fi

if [[ $1 == "" ]]; then
    echo "Voce deve referenciar um arquivo."
    exit
else
    if [[ $2 == "-caminho" ]]; then
        if [[ $3 == "" ]]; then
            echo "Voce deve referenciar um caminho para o arquivo."
            exit
        else
            TARGET_DIR=$3
            $($PYTHON_DIR $COMPILER $1 $2 $3)
        fi
    else
        if [[ $2 != "" ]]; then
            echo "Opção nao identificada!"
            exit
        fi
    fi
fi

$($PYTHON_DIR $COMPILER "$TARGET_DIR$1")
